name: deploy to glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Glitch Project Sync
        uses: kanadgupta/glitch-sync@v3.0.1
        with:
          # Auth token for your Glitch Project
          auth-token: '${{secrets.GLITCH_AUTH_TOKEN}}'
          # ID of your Glitch Project
          project-id: '${{secrets.GLITCH_PROJECT_ID}}'
